### ISSUE TITLE
ResOfExtension improvements

### ISSUE THREAD

**Issue by mradzinski** [dev-weiqi/ResOf#1]
Hey! Nice work so far. 

My only recommendation is that you might wanna think of improving `ResOfExtension`. Since you aren't controlling if the `Int` instance is actually a resource or just some random number (1, 2, 3, ...), you're basically polluting every `Int` declaration across an app with plenty of methods which 99% of the time aren't useful and just plain confusing for someone who's not aware of what ResOf does.

For example: 
- `1.asString()` should return `"1"`, not throw some exception.
- `1.asBool()` should return `true`, not throw some exception.
- `1.asInteger()` should return `1`, not throw some exception.

You might wanna have something like `Int.resOf.string()` for example. This way you nest every extension under `resOf`, indicating the actual use of it, and cleaning up `Int` instances from methods that can be interpreted as a simple `toSomeObject()` method (specially when `as` is a casting keyword).

Cheers

**Comment by dev-weiqi** [comment]
I'm very excited to receive your feedback,
Thank you so much for your useful advice, This helps me a lot! 
It also give me the motivation to continue to develop 🙌

**Comment by dev-weiqi** [comment]
ResOf [v1.1.0](https://github.com/dev-weiqi/ResOf/releases/tag/1.1.0 ) released. 🎉

**Comment by mradzinski** [comment]
Glad to be of help. You did a very clean implementation of my recommendation, so kudos to you as well! 🎉

**Comment by dev-weiqi** [comment]
I truly appreciate your help very much 🙏
