### ISSUE TITLE
activity theming not respected

### ISSUE THREAD

**Issue by kibotu** [dev-weiqi/ResOf#2]
I'm with you on passing context everywhere is one of the most annoying things in android and we need to come up with better solutions and also I like your idea using the androidx startup-runtime! 

however you might want to hook up on the ActivityLifecycleCallbacks to also use the current activity to for retrieving correct activity themed values if available. another drawback is that it doesn't work with services, e.g. workmanager, push notifications, since application context is not the correct context to retrieve the values.

here is my solution to the same problem https://github.com/kibotu/AndroidResourceExtensions

it also fails on layout themed attributes though. 

another thing is that creating wrapper classes `ResOfWrapper` for every single resource retrieval seems a bit wasteful, have you thought of using inline classes instead?

**Comment by dev-weiqi** [comment]
Sorry to reply so late, I  had myopia surgery last month🤩.
I am very grateful for your reply, but I have no good ideas for your proplems. 
If you have good suggestions, may you create a pull-request for me?
I also appreciate your inline classes suggestion, I will find time to fix it.

Your library is so amazing, I learn a lot from it! 
If I found it earlier, this lib would not be created 🤣
Thanks again for your comments !
